### ISSUE TITLE
资源加载

### ISSUE THREAD

**Issue by languyue** [page-pipepline/pipeline-template#1]
你好请问下，对于自己封装的组件。使用到的静态资源怎么管理。多个组件都会有用到静态资源

**Comment by CntChen** [comment]
静态资源是cdn资源的话化可以在 [index.html](https://github.com/page-pipepline/pipeline-template/blob/master/src/index.html) 引入.
如果是源码中的静态资源文件, 直接 import, webpack 打包就好了.
不知是否满足你的场景？
